securebanking-rcs-ui/projects/rcs/src/app/pages/consent/components/consent-box/items/rate-amount-item/rate-amount-item.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/funds-confirmation/funds-confirmation.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pipes/account-number.pipe.ts
securebanking-rcs-ui/projects/rcs/src/app/pipes/amount.pipe.ts
securebanking-rcs-ui/projects/rcs/src/app/pipes/balance.pipe.ts
securebanking-rcs-ui/projects/rcs/src/app/types/ob.ts
securebanking-rcs-ui/projects/rcs/src/environments/environment.default.ts

Note that this does not cover the consent decision endpoint, which currently does not work against a local Docker with wiremock.
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/62

62: Integrate UI with securebanking RCS

---

_infra/helm/securebanking-ui/Chart.yaml
_infra/helm/securebanking-ui/templates/auth-deployment.yaml
_infra/helm/securebanking-ui/templates/auth-svc.yaml
_infra/helm/securebanking-ui/values.yaml

Create the Helm chart for the auth service UI.
Contains a deployment and service only. The ingress will be covered by IG.

create helm chart for the authservice ui

---

_infra/helm/securebanking-ui/templates/auth-deployment.yaml
_infra/helm/securebanking-ui/values.yaml

Apply configuration for the auth ui. `DOMAIN`, `AUTHENTICATION_URL` and `DIRECTORY_BACKEND_URL` must be set.
Change the health check to `/dev/info`

apply auth service config

---

.github/workflows/merge.yml
.github/workflows/pr.yml
Makefile

Add a merge action that executes the `make docker` target. Supplies the release repo to push to.
The `docker` target will push to dev repo and release repo if `release-repo` is supplied otherwise it will push to dev only.
Remove the `latest` tag from the pr action as outlined in https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs/issues/54
Add a `version` target that will output the package.json version of the supplied ui.

Merge action

---

_infra/helm/securebanking-ui/templates/auth-deployment.yaml
_infra/helm/securebanking-ui/templates/rcs-deployment.yaml
_infra/helm/securebanking-ui/templates/swagger-deployment.yaml

The ui chart has failed to deploy to dev due to invalid `values` keyword

fix invalid template values

---

_infra/helm/securebanking-ui/templates/auth-deployment.yaml
_infra/helm/securebanking-ui/templates/rcs-deployment.yaml
_infra/helm/securebanking-ui/templates/swagger-deployment.yaml

Make a temporary change to the deployment manifests. Nginx is serving the node application and the current health checks are not being hit. The securebanking helm charts are derived from the openbanking charts and they have no health checks.
issue: https://github.com/SecureBankingAccessToolkit/securebanking-ui/issues/17

remove the ui health checks

---

_infra/helm/securebanking-ui/values.yaml

Rename the rcs ui subdomain to `rcs-ui`. The previous domain of `rcs` was conflicting with the api of the same name

rename subdomain to rcs-ui

---

.gitignore
securebanking-rcs-ui/README.md
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/consent-dev.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/domestic-payment-consent-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/vrp-payment-consent-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/components/account-selection/account-selection.component.html
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/components/consent-box/items/rate-amount-item/rate-amount-item.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-payment/domestic-payment.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-payment/domestic-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-schedule-payment/domestic-schedule-payment.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-schedule-payment/domestic-schedule-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-standing-order/domestic-standing-order.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-standing-order/domestic-standing-order.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/file-payment/file-payment.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/file-payment/file-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/funds-confirmation/funds-confirmation.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/funds-confirmation/funds-confirmation.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-payment/international-payment.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-payment/international-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-schedule-payment/international-schedule-payment.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-schedule-payment/international-schedule-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-standing-order/international-standing-order.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-standing-order/international-standing-order.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/single-payment/single-payment.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/single-payment/single-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/vrp-payment/vrp-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pipes/amount.pipe.ts
securebanking-rcs-ui/projects/rcs/src/app/types/api.ts
securebanking-rcs-ui/projects/rcs/src/app/types/consentItem.ts
securebanking-rcs-ui/projects/rcs/src/app/types/ob.ts

- Fix response object obtained from RCS
- Added mock consent for domestic-payments
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/230

230: domestic payment consent decision

---

.gitignore
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/components/account-selection/account-selection.component.html
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-payment/domestic-payment.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-schedule-payment/domestic-schedule-payment.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-standing-order/domestic-standing-order.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/file-payment/file-payment.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-payment/international-payment.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-schedule-payment/international-schedule-payment.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-standing-order/international-standing-order.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/single-payment/single-payment.component.spec.ts

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/297
- Return the selected account from the domestic payment decision as OBAccount2
- Fix the unit tests

Return selected account as OBAccount2

---

securebanking-rcs-ui/projects/rcs/src/app/pages/consent/account/account.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/account/account.component.ts
securebanking-rcs-ui/projects/rcs/src/app/types/consentItem.ts

- Modified the interface `IConsentEventEmitter` to rename the field `sharedAccounts` to `accountIds` for direct mapping on RCS backend
IssueL https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/237

237: field sharedaccounts to accountIds, direct mapping on RCS

---

securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-standing-order/domestic-standing-order.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-standing-order/international-standing-order.component.ts

https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/356

356: Date and Amount Fields in RCS-UI for the Final Payment are reversed

---

_infra/helm/securebanking-ui/templates/ingress.yaml
_infra/helm/securebanking-ui/values.yaml

Updating ingress.yaml to apiVersion: networking.k8s.io/v1
This is required to be able to upgrade the cluster to k8s 1.22
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/390

390: Updating ingress.yaml to apiVersion: networking.k8s.io/v1

---

securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/international-payment-consent-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/international-scheduled-payment-consent-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-payment/international-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-schedule-payment/international-schedule-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/types/api.ts

- Updated international payment consent details component
- Updated international scheduled payment consent details components
- Updated api classes to add the charges property and to be mapping from the rs consent details response
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/486

486: update consent components to display calculated elements

---

securebanking-rcs-ui/README.md
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/consent-dev.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/file-payment-consent-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/file-payment/file-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/types/api.ts

- Added mock for file payment consent component
- Delete unused file payment component fields from ApiResponses.ConsentDetailsResponse object
- Added instructions in rcs-ui README file to run the tests and validations before push changes
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/552

552: file payment consent details display

---

securebanking-cli-ui/scripts/buildThemes.js
securebanking-rcs-ui/projects/rcs/docker/build-settings.js

Configure the RCS UI index base href to /rcs/ui/, this means that the UI is expected to run behind a reverse proxy that uses this prefix.
See related ingress PR: https://github.com/SecureApiGateway/sapig-openbanking-uk-developer-envs/pull/20
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/805

793: Configure index base href to /rcs/ui

---

securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/domestic-payment-consent-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/domestic-scheduled-payment-response-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/domestic-standing-order-response-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/international-payment-consent-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/international-scheduled-payment-consent-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/international-standing-order-consent-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/vrp-payment-consent-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-payment/domestic-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-schedule-payment/domestic-schedule-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-standing-order/domestic-standing-order.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/file-payment/file-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-payment/international-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-schedule-payment/international-schedule-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-standing-order/international-standing-order.component.ts

Issue: https://github.com/secureapigateway/secureapigateway/issues/527
Description: Fixed the wrong displayed payee name for all Payment APIs. Also, removed the "payee name" field for the File Payment Consent since the consent response object doesn't have the creditorAccount field.

527: Fixing wrong displayed payee name

---

.github/workflows/release-rcs.yml

- Fix 'SERVICE_NAME' when call the reusable workflow to build the docker image
Issue: https://github.com/secureapigateway/secureapigateway/issues/812

Fix the job to call reusable workflow to build the docker image

---

.github/workflows/release-rcs.yml

- Updated release-rcs workflow
Issue: https://github.com/secureapigateway/secureapigateway/issues/812

Fix outputs to be passed to the reusable workflow release draft

---

.github/workflows/pr.yml
_infra/helm/securebanking-ui/Chart.yaml
_infra/helm/securebanking-ui/templates/rcs-deployment.yaml
_infra/helm/securebanking-ui/templates/rcs-svc.yaml
_infra/helm/securebanking-ui/values.yaml

The remote-consent-server-user-interface has a service called remote-consent-service-user-interface-rcs-ui which means IG is failing to call it at http://remote-consent-service-user-interface:8080
Issue: https://github.com/secureapigateway/secureapigateway/issues/933

993: Make UI reachable in the cluster

---

_infra/helm/securebanking-ui/Chart.yaml

- Updated helm chart to 1.0.3
- Align rcs-ui version to 1.0.3
Issue: https://github.com/secureapigateway/secureapigateway/issues/995

995: prepare release 1.0.2

---

secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/domestic-payment/domestic-payment.component.spec.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/domestic-payment/domestic-payment.component.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/domestic-schedule-payment/domestic-schedule-payment.component.spec.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/domestic-schedule-payment/domestic-schedule-payment.component.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/domestic-standing-order/domestic-standing-order.component.spec.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/domestic-standing-order/domestic-standing-order.component.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/file-payment/file-payment.component.spec.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/file-payment/file-payment.component.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/funds-confirmation/funds-confirmation.component.spec.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/funds-confirmation/funds-confirmation.component.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/international-payment/international-payment.component.spec.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/international-payment/international-payment.component.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/international-schedule-payment/international-schedule-payment.component.spec.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/international-schedule-payment/international-schedule-payment.component.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/international-standing-order/international-standing-order.component.spec.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/international-standing-order/international-standing-order.component.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/single-payment/single-payment.component.spec.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/single-payment/single-payment.component.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/vrp-payment/vrp-payment.component.ts

- Added condition in all submit payment decision to set null the debtor account when the consent is rejected
- Fix spec unit tests
Issue Comment: https://github.com/SecureApiGateway/SecureApiGateway/issues/1015#issuecomment-1593243912
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1015

1015: Improve decision submission when the consent is rejected

---

secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/debtorAccountProvided/vrp-payment-consent-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/vrp-payment/vrp-payment.component.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pipes/maximum-amount.pipe.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/types/api.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/types/ob.ts

The RCS API has updated the controlParameters from OBDomesticVRPControlParameters to FRDomesticVRPControlParameters. See https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rcs/pull/146
Updating UI types to be able to decode the change in json.
Issue: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rcs/pull/1032

1032: Updating VRP details types to use decode FR data model types

---

_infra/helm/securebanking-ui/Chart.yaml

- Updated helm chart version to 1.0.4
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1040

1040: prepare helm chart version to build the release 1.0.3

---

secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/debtorAccountProvided/domestic-standing-order-response-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/debtorAccountProvided/international-standing-order-consent-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/domestic-standing-order-response-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/international-standing-order-consent-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/domestic-standing-order/domestic-standing-order.component.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/international-standing-order/international-standing-order.component.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/types/api.ts

- Fixed missed standing order display data
- Updated mock test for standing orders (domestic and international payments)
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1026

1026: missed standing order (domestic and international) display consent details

---

.github/workflows/merge.yml
.github/workflows/pr.yml
.github/workflows/release-rcs.yml
Makefile
docker-compose/docker-compose.yml
secure-api-gateway-ob-uk-ui-rcs/README.md

- Change any pipelines to push to the new Artifact Registry
- Change any pipelines / packages that pull images to use the new Artifact Registry
- Change Auth to GCP pipeline command to use V2 as V0 is deprecated
Issue:
- https://github.com/SecureApiGateway/SecureApiGateway/issues/987
- https://github.com/SecureApiGateway/SecureApiGateway/issues/1202

987: Artifact Registry Migration

---

secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/account-access-consent-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/customer-info-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/debtorAccountProvided/domestic-payment-consent-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/debtorAccountProvided/domestic-scheduled-payment-response-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/debtorAccountProvided/domestic-standing-order-response-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/debtorAccountProvided/file-payment-consent-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/debtorAccountProvided/international-payment-consent-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/debtorAccountProvided/international-scheduled-payment-consent-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/debtorAccountProvided/international-standing-order-consent-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/debtorAccountProvided/vrp-payment-consent-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/domestic-payment-consent-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/domestic-scheduled-payment-response-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/domestic-standing-order-response-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/file-payment-consent-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/funds-confirmation-consent-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/international-payment-consent-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/international-scheduled-payment-consent-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/international-standing-order-consent-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent-dev/mocks/vrp-payment-consent-details.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/funds-confirmation/funds-confirmation.component.spec.ts
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/services/api.service.ts
secure-api-gateway-ob-uk-ui-rcs/sample-details-json-files/account-response-details.json
secure-api-gateway-ob-uk-ui-rcs/sample-details-json-files/domestic-scheduled-payment-response-details.json
secure-api-gateway-ob-uk-ui-rcs/sample-details-json-files/vrp-response-details.json

Spring Boot 3 is not mapping URIs with the trailing slashes to the controllers. The use of a trailing slash is incorrect and should be removed.
Issue: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rcs/pull/1245

1245: Removing trailing slash from Consent API URIs

---

_infra/helm/securebanking-ui/readme.md
_infra/helm/securebanking-ui/templates/deployment.yaml

Rename deployment-config to be core-deployment-config & ob-deployment-config
Change openig-secrets-env to core-secrets & ob-secrets
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1315

1315: Remove unwanted config from dev-core

---

Makefile

Missing space in docker command when setlatest is true
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1389

389: Use CI Repo for standardised steps in github workflows

---

.github/workflows/release-rcs.yml
Makefile

Amend release workflow to use reusable CI repo workflow
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1389

1389: Use CI Repo for standardised steps in github workflows

---

_infra/helm/securebanking-ui/Chart.yaml
secure-api-gateway-ob-uk-ui-rcs/package.json

Bump helm to `4.0.4`
Bump RCS to `4.0.4`
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1642

1642: Bump helm and rcs

---

_infra/helm/securebanking-ui/Chart.yaml

Bump helm version to `4.0.5`
Need to use 4.0.5 as 4.0.4 was released before discovering a [bug](https://github.com/SecureApiGateway/SecureApiGateway/issues/1647) in the UI
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1642

1642: Create SAPIG 4.0.4
