README.md
_infra/helm/securebanking-ui/templates/rcs-deployment.yaml
_infra/helm/securebanking-ui/templates/rcs-svc.yaml
_infra/helm/securebanking-ui/values.yaml

Create the rcs helm chart.
Apply environment variables as required by the readme:
- `TEMPLATE_NAME`
- `DOMAIN`
- `PORT`
Add to the base readme additional requirements for installing the rcs ui

add rcs helm chart

---

_infra/helm/securebanking-ui/templates/auth-deployment.yaml
_infra/helm/securebanking-ui/templates/auth-svc.yaml
_infra/helm/securebanking-ui/templates/swagger-deployment.yaml
_infra/helm/securebanking-ui/templates/swagger-svc.yaml
_infra/helm/securebanking-ui/values.yaml

Add the swagger deployment and service and add unique names for each deployment/service.
Add missing environment variables required by each readme.

add swagger deployment/svc

---

.github/workflows/pr.yml
Makefile
securebanking-rcs-ui/projects/rcs/docker/Dockerfile

Add a github action for the pr process.
Run tests and package the 3 uis in parallel after all success then package and upload a helm chart to the dev repo.

UI pr action

---

.github/workflows/merge.yml

add missing `gcloud auth configure-docker`. Docker images were failing to push due to no credentials

add gcloud auth docker

---

_infra/helm/securebanking-ui/templates/auth-deployment.yaml
_infra/helm/securebanking-ui/templates/rcs-deployment.yaml
_infra/helm/securebanking-ui/templates/swagger-deployment.yaml

add quote keyword for the port numbers. env vars must be string format.

port numbers must be quotes

---

_infra/helm/securebanking-ui/templates/auth-deployment.yaml
_infra/helm/securebanking-ui/templates/auth-svc.yaml
_infra/helm/securebanking-ui/templates/ingress.yaml
_infra/helm/securebanking-ui/templates/rcs-deployment.yaml
_infra/helm/securebanking-ui/templates/rcs-svc.yaml
_infra/helm/securebanking-ui/templates/swagger-deployment.yaml
_infra/helm/securebanking-ui/templates/swagger-svc.yaml
_infra/helm/securebanking-ui/values.yaml

Create an ingress for the individual uis.
Supply the subdomains as config and use this to identify the individual services/deployments
Change the deployment port to 80 given that NGinx is serving the application

Apply ingress

---

.github/workflows/merge.yml
.github/workflows/pr.yml

Deploy to developer environments when prs are raised and tag with `latest` and git sha short when merged to master.
issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/89

tag with pr number and deploy

---

_infra/helm/securebanking-ui/templates/rcs-deployment.yaml
_infra/helm/securebanking-ui/templates/swagger-deployment.yaml
_infra/helm/securebanking-ui/values.yaml
securebanking-rcs-ui/projects/rcs/docker/Dockerfile
securebanking-rcs-ui/projects/rcs/docker/deployment-settings.js
securebanking-rcs-ui/projects/rcs/docker/start.sh
securebanking-rcs-ui/projects/rcs/src/app/services/api.service.ts
securebanking-rcs-ui/projects/rcs/src/environments/environment.default.ts
securebanking-rcs-ui/projects/rcs/src/environments/environment.dev.default.ts
securebanking-rcs-ui/projects/rcs/src/environments/environment.dev.ts
securebanking-rcs-ui/projects/rcs/src/environments/environment.local.ts
securebanking-rcs-ui/projects/rcs/src/environments/environment.prod.ts
securebanking-rcs-ui/projects/rcs/src/environments/environment.ts
service-build.md

- Deleted env parameters from docker
- Created env parameters on helm chart to personalise the environment namespace with the proper values for
- Template them
- authorisation server
- remote consent server
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/95

95: environment specific values

---

_infra/helm/securebanking-ui/templates/ingress.yaml
_infra/helm/securebanking-ui/templates/rcs-deployment.yaml
_infra/helm/securebanking-ui/templates/rcs-svc.yaml
_infra/helm/securebanking-ui/templates/swagger-deployment.yaml
_infra/helm/securebanking-ui/templates/swagger-svc.yaml
_infra/helm/securebanking-ui/values.yaml
securebanking-rcs-ui/projects/rcs/docker/deployment-settings.js
securebanking-rcs-ui/projects/rcs/docker/start.sh
securebanking-rcs-ui/projects/rcs/src/environments/environment.default.ts
securebanking-rcs-ui/projects/rcs/src/environments/environment.dev.ts
securebanking-rcs-ui/projects/rcs/src/environments/environment.local.ts
securebanking-rcs-ui/projects/rcs/src/environments/environment.prod.ts
securebanking-swagger-ui/projects/swagger/docker/deployment-settings.js
securebanking-swagger-ui/projects/swagger/docker/start.sh
securebanking-swagger-ui/projects/swagger/src/environments/environment.default.ts

- Unified values
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/95

95: specific environment values

---

securebanking-rcs-ui/projects/rcs/src/app/pages/consent/account/account.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/account/account.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/consent.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-payment/domestic-payment.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-payment/domestic-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-schedule-payment/domestic-schedule-payment.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-schedule-payment/domestic-schedule-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-standing-order/domestic-standing-order.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/domestic-standing-order/domestic-standing-order.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/file-payment/file-payment.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/file-payment/file-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/funds-confirmation/funds-confirmation.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/funds-confirmation/funds-confirmation.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-payment/international-payment.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-payment/international-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-schedule-payment/international-schedule-payment.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-schedule-payment/international-schedule-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-standing-order/international-standing-order.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/international-standing-order/international-standing-order.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/single-payment/single-payment.component.spec.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent/single-payment/single-payment.component.ts
securebanking-rcs-ui/projects/rcs/src/app/types/ConsentDecision.ts

- Fix status from 'Approved' to 'Authorised"
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/103

103: Consent decision status fix

---

.github/workflows/merge.yml
.github/workflows/pr.yml
.github/workflows/release.yml
_infra/helm/securebanking-ui/templates/rcs-deployment.yaml
securebanking-rcs-ui/projects/rcs/docker/deployment-settings.js
securebanking-rcs-ui/projects/rcs/docker/start.sh
securebanking-swagger-ui/projects/swagger/docker/deployment-settings.js
securebanking-swagger-ui/projects/swagger/docker/start.sh

- Updated github actions for gcloud environment configuration
- Updated deployment to normalize properties from `platform-config` map
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/229

229: cdk-cdm-fidc same configuration

---

securebanking-rcs-ui/projects/rcs/docker/build-settings.js
securebanking-rcs-ui/projects/rcs/docker/deployment-settings.js
securebanking-swagger-ui/projects/swagger/docker/deployment-settings.js

Added `https://` to all `fqdn` properties for deployments

Fix deployment-settings interpolation values

---

securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/consent-dev.component.ts
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/international-scheduled-payment-consent-details.js

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/406

406: International scheduled payment get consent details

---

securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/account-access-consent-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/domestic-payment-consent-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/domestic-scheduled-payment-response-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/domestic-standing-order-response-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/file-payment-consent-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/international-payment-consent-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/international-scheduled-payment-consent-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/international-standing-order-consent-details.js
securebanking-rcs-ui/projects/rcs/src/app/pages/consent-dev/mocks/vrp-payment-consent-details.js
securebanking-rcs-ui/projects/rcs/src/app/services/api.service.ts
securebanking-rcs-ui/sample-details-json-files/account-response-details.json
securebanking-rcs-ui/sample-details-json-files/domestic-scheduled-payment-response-details.json
securebanking-rcs-ui/sample-details-json-files/vrp-response-details.json

To be compatible with rcs change: https://github.com/SecureApiGateway/securebanking-openbanking-uk-rcs/pull/87
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/805

805: Updating rcs backend request paths

---

_infra/helm/securebanking-ui/templates/ingress.yaml

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/793

793: Removing rcs-ui from securebanking-ui ingress

---

_infra/helm/securebanking-ui/templates/rcs-deployment.yaml
securebanking-rcs-ui/projects/rcs/docker/deployment-settings.js
securebanking-rcs-ui/projects/rcs/docker/start.sh

See related IG PR: https://github.com/SecureApiGateway/securebanking-openbanking-uk-gateway/pull/305
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/805

805: Configure UI to make calls to RCS API via IG route

---

securebanking-rcs-ui/projects/rcs/src/app/pages/consent/components/consent-box/items/vrp-account-item/vrp-account-item.component.html
securebanking-rcs-ui/projects/rcs/src/app/pipes/account-number-domestic-vrp.pipe.ts
securebanking-rcs-ui/projects/rcs/src/app/pipes/pipes.module.ts

Issue: https://github.com/secureapigateway/secureapigateway/issues/738
Description: Fixed account number format for VRP payments.

738: Fixing account number format for VRP payments

---

.github/dependabot.yml

Issue: https://github.com/secureapigateway/secureapigateway/issues/889

889: Enable dependabot PRs

---

README.md

Point out 3rd party security issues with the UIs and warn users to use these UIs with caution

Update readme with warning

---

_infra/helm/securebanking-ui/templates/rcs-deployment.yaml

Issue: https://github.com/secureapigateway/secureapigateway/issues/851

851: Remove subdomain from deployment name

---

.github/workflows/merge.yml
.github/workflows/pr.yml

- Updated pr workflow to fix the service name passed to codefresh pipeline
- Updated merge workflow to fix the service name passed to codefresh pipeline
Issue: https://github.com/secureapigateway/secureapigateway/issues/932

932: Fix service name prefix variable passed to codefresh pipeline

---

secure-api-gateway-ob-uk-ui-rcs/package-lock.json
secure-api-gateway-ob-uk-ui-rcs/package.json

- Updated rcs-ui version to 0.9.1 to make ready to build the release
Issue: https://github.com/secureapigateway/secureapigateway/issues/932

932: update rcs-ui version to 0.9.1

---

.github/workflows/release-rcs.yml

- Release rcs workflow updated to signing the commits
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/812

812: added support to signing commit to rcs release workflow

---

secure-api-gateway-ob-uk-ui-rcs/package-lock.json
secure-api-gateway-ob-uk-ui-rcs/package.json

- package and package-lock updated to version 1.0.0
Issue: https://github.com/secureapigateway/secureapigateway/issues/927

927: Update rcs-ui version to 1.0.0

---

_infra/helm/securebanking-ui/Chart.yaml
secure-api-gateway-ob-uk-ui-rcs/package-lock.json
secure-api-gateway-ob-uk-ui-rcs/package.json

- Updated helm chart to 1.0.2
- Updated ui-rcs package descriptors version to 1.0.3
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/969

969: updated versions to build release 1.0.1 of SAPIG

---

_infra/helm/securebanking-ui/Chart.yaml
secure-api-gateway-ob-uk-ui-rcs/package-lock.json
secure-api-gateway-ob-uk-ui-rcs/package.json

- Upgrade rcs ui version to 2.0.0
- Upgrade helm chart version to 2.0.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1099

1099: upgrade rcs ui and helm chart release version

---

_infra/helm/securebanking-ui/templates/deployment.yaml
_infra/helm/securebanking-ui/values.yaml

Add in affinity codeblock but have way of adding affinity codeblock, not required for dev
Issue: https://bugster.forgerock.org/jira/browse/SAPIG-237

SAPIG-237: Add Affinity codeblock to SAPIG components

---

_infra/helm/securebanking-ui/Chart.yaml
secure-api-gateway-ob-uk-ui-rcs/package-lock.json
secure-api-gateway-ob-uk-ui-rcs/package.json

- Updated helm chart version and package to 2.2.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1182

Prepare release 2.2.0

---

.github/workflows/release-rcs.yml
_infra/helm/securebanking-ui/Chart.yaml
secure-api-gateway-ob-uk-ui-rcs/package-lock.json
secure-api-gateway-ob-uk-ui-rcs/package.json

Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1251

1251: Bump versions and workflow fix for pipeline

---

.github/workflows/merge.yml
.github/workflows/pr.yml
.github/workflows/release-rcs.yml

Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1264

1264: Update actions that have deprecations

---

.github/workflows/release-rcs.yml

Commit directly to master instead of having a PR to approve and merge
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1260

1260: Investigate PR runs for GitHub user

---

.github/workflows/merge.yml
.github/workflows/pr.yml
.github/workflows/slackNotification.yml

Standardise some of the worklows, minimum changes for now
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1389

1389: Use CI Repo for standardised steps in github workflows

---

_infra/helm/securebanking-ui/Chart.yaml
secure-api-gateway-ob-uk-ui-rcs/package-lock.json
secure-api-gateway-ob-uk-ui-rcs/package.json

Update Helm and RCS Versions
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1404

1404: Create and Release SAPIG Core and OB

---

.github/workflows/merge.yml
.github/workflows/pr-helm.yml
.github/workflows/pr.yml

Enable manual trigger for PR and Merge workflows
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1465

1465: Allow Manual run of workflows

---

secure-api-gateway-ob-uk-ui-rcs/package.json

Update Helm and RCS Version to `3.1.0`
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1476

1476: Build and Deploy SAPIG 3.1.0 to relenv

---

_infra/helm/securebanking-ui/Chart.yaml
secure-api-gateway-ob-uk-ui-rcs/package-lock.json

Merge master branch into ob-v4
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1520

1520: Fix Rebase Conflicts post 3.2.0 Release

---

_infra/helm/securebanking-ui/Chart.yaml
secure-api-gateway-ob-uk-ui-rcs/package.json

Bump helm & RCS Version
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1602

1602: Build and Deploy SAPIG 4.0.0

---

secure-api-gateway-ob-uk-ui-rcs/projects/rcs/src/app/pages/consent/consent.component.ts

This commit adds some debug and should make it easier to set breakpoints in the browser dev tools.
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1647

1647: Fix Consent UI loading issue

---

_infra/helm/securebanking-ui/readme.md
_infra/helm/securebanking-ui/templates/deployment.yaml
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/docker/deployment-settings.js
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/docker/local.env
secure-api-gateway-ob-uk-ui-rcs/projects/rcs/docker/start.sh
service-build.md

Rename ob-deployment-config & ob-secrets to rs-sapig
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1676

1676: Split IG into AS/RS and deploy to Devenvs
